nome= str(input('Digite seu nome completo')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculo é: {}'.format(nome.upper()))
print('Seu nome em minúsculo é: {}'.format(nome.lower()))
print('Seu nome tem o total de {} letras:'.format(len(nome) - nome.count(' ')))
print('Seu nome primeiro nome tem o total de {} letra'.format(nome.find(' ')))